### PR TITLE
Make "last updated" date an ENV var and use <time> tag

### PR DESCRIPTION
**Pull request by pcraig3**
This story was something I was working on last week and then I finished just now. 

It's so stupid, actually. The thing we want is so simple.

**Note: edited the content below to reflect changes**

This pull request adds a `LAST_UPDATED` ISO date to `.env.public`, and then it converts the the date in the env var into a [`<time>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) element with the right format on the start page. 

The upside is that it will be more semantic to to it this way. The downside is that it's a lot more code for a pretty small problem.

Here's the idea:
1. Update `LAST_UPDATED` env var in `.env.public`
2. If `LAST_UPDATED` exists, add a `<time>` element to the "last modified" `h2` on the landing page
   1.  (if we see `LAST_UPDATED` we kind of assume it's a valid date string)
3. Set the `datetime=` attribute as `LAST_UPDATED`
4. Use `lastmodified` filter to convert `LAST_UPDATED` into the format we expect

If there is no `LAST_UPDATED`, we hide the `h2`.

✨  Ta da! ✨ 

Up for discussion: 

- Do we even care about this? Could just leave it as a manual process.

### Screenshot

_The only change to this screenshot is that the attribute says `datetime="2020-04-16"` now, without info about time of day._

| en | fr |
|--------|-------|
|   Screen Shot 2020-04-16 at 6 48 15 PM  | Screen Shot 2020-04-16 at 6 48 12 PM   |

### CODE REVIEW

**Comment by CalvinRodo** [comment]
That value is the update date for the benefits, not the site itself. 

See Courtney's comments here: https://github.com/cds-snc/c19-benefits-node/issues/256

I was also under the impression it worked the same way you did.

**Comment by pcraig3** [comment]
No worries! Will update this so it's a var we set in `.env.public`, which makes things easier.

**Comment by CalvinRodo** [comment]
looks like Date Modified is required in the footer although for applications you can use the version instead. 

image

**Comment by pcraig3** [comment]
> looks like Date Modified is required in the footer although for applications you can use the version instead.

Is a SHA an acceptable version string?

**Pull request merged**
